theme: jekyll-theme-minimal
title: Nate Powell
email: poweln@rpi.edu
description: Doctoral student at Rensslaer Polytechnic Institute 
baseurl: /natepowell81.github.io

gems:
    - jekyll-pdf


# Social Sharing
twitter:
  username               : &twitter
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :  # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Site Author
author:
  name             : np
  avatar           : me.png
  bio              : Cognitive Scientist
  location         : Troy, NY
  employer         :
  googlescholar    : 
  email            :
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : natepowell81
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         :
  orcid            : 
  pinterest        :
  soundcloud       :
  stackoverflow    : # http://stackoverflow.com/users/123456/username
  steam            :
  tumblr           :
  twitter          : nvpowell
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :
